name: cgrep
description: Easily usable column-based grep tool with advanced expression, regex and varaibles. An intutive alternative to awk.
version: 1.5.1
homepage: https://github.com/cgrep-tool/cgrep
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

executables:
  cgrep:

dependencies:
  args: 

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
